language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
env:
  global:
    - CODECLIMATE_REPO_TOKEN=26fadb16d2a01ff66c1fecf2c74438fcb372119d64f3ab2aab8257ceb13c35e8
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/556fa7e78f49c2f0016e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
